name: PortChuuExtras
main: sh.chuu.port.mc.portchuuextras.PortChuuExtras
version: @version@
description: Port Chuu Extra Plugin
api-version: 1.15
author: Simon Chuu
website: https://port.chuu.sh
softdepend: [ProtocolLib]

commands:
  op:
    aliases: [summontnt]
    description: idk why did i make this
    usage: /op <name>
    permission: portchuuextras.command.op
  xray:
    aliases: [selfban]
    description: idk why did i make this
    usage: /xray
    permission: portchuuextras.command.xray
  # Contributor Commands
  simonorj:
    aliases: [chuu]
    description: idk why did i make this
    usage: /simonorj
    permission: portchuuextras.command.simonorj
  thecodingguy:
    aliases: [tcg]
    description: A thing by TCG, b/c why not
    usage: /thecodingguy
    permission: portchuuextras.command.thecodingguy

permissions:
  portchuuextras.command.xray:
    default: true
  portchuuextras.command.op:
    default: true
  # Contributor Commands
  portchuuextras.command.simonorj:
    default: true
  portchuuextras.command.thecodingguy:
    default: true
  # Listener Commands
  portchuuextras.interact.sit:
    default: true
